#colorscheme nord

set global indentwidth 0
set global aligntab true

add-highlighter global/ show-matching
add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ wrap
add-highlighter global/ regex \b(TODO|FIXME|XXX|NOTE)\b 0:default,rgb:5e81ac+b
add-highlighter global/ ranges show_matching_insert

map global normal '<a-\>' '<a-i>w:ctags-search<ret>'

hook global WinCreate ^[^*]+$ %{editorconfig-load}
